local options = {
  shell = "/bin/zsh",
  number = true,                           -- set numbered lines
  cursorline = true,                       -- highlight the current line
  expandtab = true,                        -- tabs are spaces
  shiftwidth = 2,                          -- the number of spaces inserted for each indentation
  tabstop = 2,                             -- insert 2 spaces for a tab
  softtabstop = 2,
  colorcolumn = "120",
  hlsearch = false,                        -- do not highlight search results
  inccommand = "split",                    -- Live preview for search and replace
  splitright = true,                       -- always open vsplit right
  splitbelow = true,                       -- always open splits below
  scrolloff = 10,                          -- keep at least 10 lines above/below
  sidescrolloff = 5,                       -- keep at least 5 lines right/left
  cmdheight = 2,                           -- Give more space for displaying messages
  undofile = true,                         -- local history, enable persistent undo
  termguicolors = true,                    -- set term gui colors (most terminals support this)
  autowriteall = true,                     -- Automatically write files on :next, :make, etc
  autoread = true,                         -- trigger `autoread` when files changes on disk
  hidden = true,                           -- Hide buffers instead of closing them (useful for switching between files)
  completeopt = { "menu", "menuone", "noselect" }, -- mostly just for cmp, autocomplete options

}

for k, v in pairs(options) do
  vim.opt[k] = v
end

vim.opt.path = ".,,**"               -- Search within subfolders by default
-- But ignore noise
vim.opt.path:remove(".git,build,node_modules,public,_site,third_party")
vim.opt.wildignore:append("*.pyc")              -- Ignore autogenerated files
vim.opt.wildignore:append(".git")              -- Ignore source control
-- Ignore lib/ dirs since the contain compiled libraries typically
vim.opt.wildignore:append("build,node_modules,public,_site")
-- Ignore images and fonts
vim.opt.wildignore:append("*.gif,*.jpg,*.jpeg,*.otf,*.png,*.svg,*.ttf")
vim.opt.wildignorecase = true                          -- Ignore case when completing

vim.g.nobackup = true                         -- Don't use backup files, we have Git for that
vim.g.noswapfile = true
vim.g.nowritebackup = true

-- OscYank related stuff
vim.g.oscyank_term = "tmux"

if vim.fn.executable('rg') == 1 then
  vim.opt.grepprg = 'rg --no-heading --vimgrep --follow'
  vim.opt.grepformat = "%f:%l:%c:%m"
else
  vim.notify('rg is not available', vim.log.levels.WARN)
end
